"""Usage and descriptions for the console command reference.

The core carries none of this: every Help field in Chat.cpp is empty, and the world
`command` table that is supposed to fill them has 25 rows. So the names, security
levels and console flags are generated from the source by gen_commands.py, and the
prose lives here.

Argument strings follow the handlers' own parsing, not an external guide:
  <required>   [optional]   a|b   literal words in plain text
A trailing [player] is the core's ExtractPlayerTarget, which falls back to the selected
unit in game and therefore needs a name when the command is run from this panel.

Anything missing from NOTES still appears in the reference with its name, security
level and console flag. Add entries here rather than inventing them in the template.
"""

# Top-level commands sorted by what they are for, since alphabetical order puts
# `ban` next to `bank` and `reload` three screens from `server`. Every group in
# GROUPS must appear here exactly once; gen_commands.py enforces that, so a command
# family added to the core cannot quietly go missing from the reference.
CATEGORIES = [
    ("Server operation", [
        "server", "saveall", "quit", "service", "announce", "notify", "pbcast",
        "log", "variable", "wareffort", "event",
    ]),
    ("Accounts and moderation", [
        "account", "ban", "baninfo", "banlist", "unban", "kick", "mute", "unmute",
        "spamer", "antispam", "gm", "ticket", "whispers", "channel", "sniff",
        "anticheat",
    ]),
    ("Characters", [
        "character", "pinfo", "pdump", "reset", "levelup", "learn", "unlearn",
        "maxskill", "setskill", "repairitems", "revive", "honor", "guild",
        "groupinfo", "group", "quest", "taxicheat", "explorecheat", "showarea",
        "hidearea", "removeriding", "gold", "save", "start", "unstuck", "wr",
        "modify",
    ]),
    ("Items and inventory", [
        "additem", "additemset", "deleteitem", "itemmove", "send", "bank", "stable",
        "auction",
    ]),
    ("Teleport and movement", [
        "go", "goname", "namego", "groupgo", "gocorpse", "tele", "recall",
        "neargrave", "cometome",
    ]),
    ("Bots and test harness", [
        "partybot", "battlebot", "raidguild", "harness", "bot", "ahbot",
    ]),
    ("Inspection and lookup", [
        "lookup", "list", "unit", "spell", "instance", "trigger", "gps", "guid",
        "distance", "angle", "movegens", "commands", "help",
    ]),
    ("World building", [
        "npc", "gobject", "wp", "escort", "pool", "pet", "linkgrave", "respawn",
        "wchange", "cinematic", "video",
    ]),
    ("In-game GM actions", [
        "cheat", "aura", "unaura", "nameaura", "die", "namedie", "damage",
        "aoedamage", "fear", "freeze", "unfreeze", "possess", "charge", "knockback",
        "demorph", "mount", "dismount", "hover", "cast", "combatstop", "cooldown",
        "pvp", "bg", "deplenish", "replenish",
    ]),
    ("Database reload", ["reload"]),
    ("Developer and debug", ["debug", "mmap", "world", "groupspell"]),
]

# One line per top-level command, shown as the section header's subtitle.
GROUPS = {
    "account": "Create, inspect and change game accounts.",
    "additem": "Put an item in the selected player's bags.",
    "additemset": "Add every item belonging to an item set.",
    "ahbot": "Auction house bot.",
    "angle": "Report the facing angle between you and your target.",
    "announce": "Server-wide chat announcement.",
    "anticheat": "Anticheat state for the selected player.",
    "antispam": "Chat spam filter word list.",
    "aoedamage": "Deal damage to everything around you.",
    "auction": "Open an auction house window remotely.",
    "aura": "Apply an aura to the selected unit.",
    "ban": "Ban accounts, characters and addresses.",
    "baninfo": "Why a ban was applied and when it lifts.",
    "bank": "Open your bank from anywhere.",
    "banlist": "List current bans.",
    "battlebot": "Battleground bots.",
    "bg": "Battleground instance control.",
    "bot": "Random world-population bots.",
    "cast": "Force a spell cast for testing.",
    "channel": "Join or leave a chat channel as a GM.",
    "character": "Character maintenance: rename, level, erase, restore.",
    "charge": "Charge at the selected target.",
    "cheat": "Per-session cheat toggles. Each takes on|off, or nothing to report state.",
    "cinematic": "Author and preview cinematic camera paths.",
    "combatstop": "Drop the selected unit out of combat.",
    "cometome": "Make the selected creature walk to you.",
    "commands": "List every command your security level can run.",
    "cooldown": "Inspect and clear spell cooldowns.",
    "damage": "Apply damage to the selected unit.",
    "debug": "Developer probes. Mostly needs a player session and a selected unit.",
    "deleteitem": "Remove an item from the selected player.",
    "demorph": "Restore the selected unit's real model.",
    "deplenish": "Drain the selected unit's health and power.",
    "die": "Kill the selected unit.",
    "dismount": "Dismount yourself.",
    "distance": "Distance from you to the selected unit.",
    "escort": "Author escort waypoint paths.",
    "event": "Game events: list, start, stop, enable, disable.",
    "explorecheat": "Reveal or hide the whole map for a player.",
    "fear": "Fear the selected unit.",
    "freeze": "Freeze a player in place.",
    "gm": "Game master mode and visibility.",
    "go": "Teleport yourself. Needs a player session, so not usable from this panel.",
    "gobject": "Create, move and inspect game object spawns.",
    "gocorpse": "Teleport to a player's corpse.",
    "gold": "Remove gold from a player.",
    "goname": "Teleport to a named player.",
    "gps": "Print your exact position, map, zone and area.",
    "group": "Act on everyone in the selected player's group.",
    "groupgo": "Teleport a whole group to you.",
    "groupinfo": "Show a player's group membership.",
    "groupspell": "Spell group stacking rules.",
    "guid": "GUID of the selected unit.",
    "guild": "Create, rename, delete guilds and manage membership.",
    "harness": "Test harness primitives, used by contrib/harness suites.",
    "help": "Help for one command.",
    "hidearea": "Hide an explored area from a player's map.",
    "honor": "Honor points, kills and ranking.",
    "hover": "Toggle hover on the selected unit.",
    "instance": "Instance bindings, saves and encounter data.",
    "itemmove": "Move an item between your own bag slots.",
    "kick": "Disconnect a player.",
    "knockback": "Knock the selected unit back.",
    "learn": "Teach spells, skills and recipes.",
    "levelup": "Raise or lower a player's level.",
    "linkgrave": "Link a graveyard to a zone.",
    "list": "Find spawns and item copies in the world.",
    "log": "Per-player logging switches.",
    "lookup": "Search the game and account databases by name.",
    "maxskill": "Cap every skill the player has.",
    "mmap": "Movement map (pathfinding) diagnostics.",
    "modify": "Change a stat on the selected player. Most take one number.",
    "mount": "Apply a mount display to yourself.",
    "movegens": "Movement generator stack for the selected unit.",
    "mute": "Silence a player's chat for a while.",
    "nameaura": "Apply an aura to a named player.",
    "namedie": "Kill a named player.",
    "namego": "Summon a named player to you.",
    "neargrave": "Nearest graveyard to your position.",
    "notify": "Screen-centre notification to every player.",
    "npc": "Create, edit, move and delete creature spawns.",
    "partybot": "Party bots. Run these in game: they act on your party and selection.",
    "pbcast": "Background broadcast queue statistics.",
    "pdump": "Dump a character to a file, or load one back.",
    "pet": "Pet creation and training.",
    "pinfo": "Account, level, money and location for one player.",
    "pool": "Spawn pool inspection and forced rolls.",
    "possess": "Take direct control of the selected unit.",
    "pvp": "PvP flag for the selected player.",
    "quest": "Give, complete and remove quests.",
    "quit": "Shut the server down immediately. Console only.",
    "raidguild": "Persistent bot raid guild.",
    "recall": "Return a player to where they were last teleported from.",
    "reload": "Re-read one world database table with no restart.",
    "removeriding": "Remove riding skill from a player.",
    "repairitems": "Repair everything a player is wearing.",
    "replenish": "Refill the selected unit's health and power.",
    "reset": "Reset a character's talents, stats, spells or level.",
    "respawn": "Respawn every creature near you.",
    "revive": "Resurrect a player.",
    "save": "Write your own character to the database.",
    "saveall": "Write every online character to the database.",
    "send": "Send mail, money or items, to one player or a race mask.",
    "server": "World server state, limits, MOTD and shutdown.",
    "service": "Bulk maintenance jobs.",
    "setskill": "Set one skill's value on the selected player.",
    "showarea": "Reveal one map area to a player.",
    "sniff": "Packet capture for the selected session.",
    "spamer": "Mute accounts flagged by the spam filter.",
    "spell": "Spell template inspection.",
    "stable": "Open the hunter stable from anywhere.",
    "start": "Teleport yourself to your race's starting area.",
    "taxicheat": "Unlock every flight path for a player.",
    "tele": "Named teleport locations from game_tele.",
    "ticket": "GM ticket queue.",
    "trigger": "Area trigger inspection.",
    "unaura": "Remove an aura from the selected unit.",
    "unban": "Lift a ban.",
    "unfreeze": "Release a frozen player.",
    "unit": "Read fields off the selected unit.",
    "unlearn": "Remove spells from a player.",
    "unmute": "Restore a muted player's chat.",
    "unstuck": "Teleport yourself to your bind point.",
    "variable": "Read and write world variables.",
    "video": "Camera helpers for recording.",
    "wareffort": "AQ war effort resource tracking.",
    "wchange": "Set the weather in your current zone.",
    "whispers": "Accept or refuse whispers while in GM mode.",
    "world": "World update timing and visibility diagnostics.",
    "wp": "Creature waypoint path authoring.",
    "wr": "Reload your own character's waypoints.",
}

# (arguments, description) keyed by full command name.
NOTES = {
    # ---------------------------------------------------------------- accounts
    "account": ("", "Your own account's security level and expansion."),
    "account characters": ("<account>", "Every character on an account."),
    "account create": ("<account> <password>",
                       "Create an account at Player level. Both fields are uppercased "
                       "and the password is capped at 16 characters."),
    "account delete": ("<account>", "Delete an account and all of its characters."),
    "account lock": ("on|off", "Lock your own account to the address you last used."),
    "account onlinelist": ("[limit]", "Accounts with a session open right now."),
    "account password": ("<old> <new> <new again>", "Change your own password."),
    "account set addon": ("[account] <expansion>", "Expansion level the account may log in at."),
    "account set gmlevel": ("[account] <0-7> [realm]",
                            "Security level, written to account_access. Realm -1 means "
                            "every realm."),
    "account set locked": ("[account] <0|1>", "Pin the account to its last used address."),
    "account set password": ("<account> <new> <new again>", "Set another account's password."),

    # ---------------------------------------------------------------- bans
    "ban account": ("<account> <duration> <reason>",
                    "Duration is -1 for permanent, or a count with a unit: 10m, 2h, 7d."),
    "ban allip": ("<account> <duration> <reason>",
                  "Ban every address the account has logged in from."),
    "ban character": ("<character> <duration> <reason>", "Ban one character by name."),
    "ban ip": ("<address> <duration> <reason>", "Ban a source address."),
    "ban note": ("<character> <note>", "Attach a note to a character's record."),
    "ban warn": ("<character> <reason>", "Record a warning without banning."),
    "baninfo account": ("<account>", "When the ban was set, by whom, and when it lifts."),
    "baninfo character": ("<character>", "Ban detail for one character."),
    "baninfo ip": ("<address>", "Ban detail for one address."),
    "banlist account": ("[filter]", "Banned accounts, optionally filtered by name."),
    "banlist character": ("[filter]", "Banned characters."),
    "banlist ip": ("[filter]", "Banned addresses."),
    "unban account": ("<account>", "Lift an account ban."),
    "unban character": ("<character>", "Lift a character ban."),
    "unban ip": ("<address>", "Lift an address ban."),

    # ---------------------------------------------------------------- server
    "server info": ("", "Core revision, players online and uptime."),
    "server motd": ("", "Show the current message of the day."),
    "server set motd": ("<text>", "Set the message of the day."),
    "server set botcombatlog": ("on|off", "Verbose party bot combat logging."),
    "server set restedxp": ("[toggle] on|off", "Rested experience accrual."),
    "server plimit": ("<count>|player|moderator|gamemaster|administrator|reset",
                      "Player cap, applied live. A security keyword restricts login to "
                      "that level and above instead of capping a count."),
    "server shutdown": ("<seconds> [exitcode]",
                        "Countdown, then save every character and exit."),
    "server shutdown cancel": ("", "Call off a scheduled shutdown."),
    "server restart": ("<seconds> [exitcode]", "Countdown, then exit with the restart code."),
    "server restart cancel": ("", "Call off a scheduled restart."),
    "server idleshutdown": ("<seconds> [exitcode]", "Shut down once the server goes idle."),
    "server idleshutdown cancel": ("", "Call off an idle shutdown."),
    "server idlerestart": ("<seconds> [exitcode]", "Restart once the server goes idle."),
    "server idlerestart cancel": ("", "Call off an idle restart."),
    "server corpses": ("", "Sweep expired player corpses."),
    "server resetallraids": ("", "Clear every raid instance binding on the realm."),
    "server log filter": ("<filter> on|off", "Toggle one log filter at runtime."),
    "server log level": ("<0-3>", "Global log verbosity."),
    "server exit": ("", "Exit immediately without a countdown."),
    "saveall": ("", "Flush every online character to the database."),
    "quit": ("", "Exit immediately. Console only."),

    # ---------------------------------------------------------------- players
    "kick": ("[player]", "Disconnect a player."),
    "mute": ("[player] <minutes> <reason>", "Silence a player's chat."),
    "unmute": ("[player]", "Restore chat for a muted player."),
    "pinfo": ("[player]", "Account, security, level, money, map and guild in one line."),
    "revive": ("[player]", "Resurrect with full health."),
    "repairitems": ("[player]", "Repair everything the player is wearing."),
    "groupinfo": ("[player]", "Group the player is in, and its members."),
    "commands": ("", "Every command your security level can run."),
    "help": ("<command>", "Help text for one command, if the world table carries any."),

    "character rename": ("[player]", "Force a rename at the player's next login."),
    "character level": ("[player] <level>", "Set a character's level."),
    "character reputation": ("[player]", "Every faction standing the character holds."),
    "character hasitem": ("<item id> [player]", "Whether the character holds an item."),
    "character erase": ("<character>", "Delete a character outright, no restore."),
    "character deleted list name": ("<filter>", "Soft-deleted characters by name."),
    "character deleted list account": ("<account>", "Soft-deleted characters on an account."),
    "character deleted restore": ("<character> [new name] [account]",
                                  "Bring a soft-deleted character back."),
    "character deleted delete": ("<character>", "Purge a soft-deleted character."),
    "character deleted old": ("[days]", "Purge soft-deleted characters older than N days."),
    "character clean items": ("", "Strip items that no longer exist in item_template."),
    "character clean todelete": ("", "Run the pending character deletion queue."),
    "character race": ("<character> <race id>", "Change a character's race."),
    "character skin": ("<character> <skin id>", "Change a character's skin colour."),
    "character aiinfo": ("[player]", "Bot AI state for a character, if it is a bot."),
    "character fillflys": ("[player]", "Unlock every flight path."),

    # ---------------------------------------------------------------- lookup
    "lookup account name": ("<text> [limit]", "Accounts whose name contains the text."),
    "lookup account email": ("<text> [limit]", "Accounts by email address."),
    "lookup account ip": ("<address> [limit]", "Accounts that have used an address."),
    "lookup account iponline": ("<address> [limit]", "Accounts on an address right now."),
    "lookup player name": ("<text> [limit]", "Find the account behind a character name."),
    "lookup player account": ("<account> [limit]", "Characters belonging to an account."),
    "lookup player email": ("<email> [limit]", "Characters behind an email address."),
    "lookup player ip": ("<address> [limit]", "Characters behind an address."),
    "lookup player character": ("<text> [limit]", "Characters whose name contains the text."),
    "lookup guild": ("<text>", "Guilds by name."),
    "lookup creature": ("<text>", "Creature templates by name."),
    "lookup item": ("<text>", "Items by name."),
    "lookup spell": ("<text>", "Spells by name."),
    "lookup quest": ("<text>", "Quests by title."),
    "lookup faction": ("<text>", "Factions by name."),
    "lookup area": ("<text>", "Areas by name."),
    "lookup tele": ("<text>", "Named teleport locations."),
    "lookup skill": ("<text>", "Skills by name."),
    "lookup taxinode": ("<text>", "Flight points by name."),
    "lookup event": ("<text>", "Game events by description."),
    "lookup object": ("<text>", "Game object templates by name."),
    "lookup pool": ("<text>", "Spawn pools by description."),

    "list creature": ("<creature id> [count]", "Where a creature entry is spawned."),
    "list object": ("<object id> [count]", "Where a game object entry is spawned."),
    "list item": ("<item id> [count]", "Who holds copies of an item."),
    "list talents": ("", "Talent spells known by the selected player."),
    "list auras": ("", "Auras on the selected unit."),
    "list maps": ("", "Loaded maps and their instance counts."),

    # ---------------------------------------------------------------- mail
    "send message": ("[player] <text>", "Pop a system message on one player's screen."),
    "send mail": ('[player] "subject" "body"', "Mail with no attachment."),
    "send money": ('[player] "subject" "body" <copper>', "Mail carrying money."),
    "send items": ('[player] "subject" "body" <item>:<count> ...',
                   "Mail carrying up to twelve item stacks."),
    "send mass mail": ('<race mask>|all "subject" "body"', "Mail to every matching character."),
    "send mass money": ('<race mask>|all "subject" "body" <copper>', "Money to every match."),
    "send mass items": ('<race mask>|all "subject" "body" <item>:<count> ...',
                        "Items to every match."),
    "announce": ("<text>", "Server-wide chat announcement."),
    "notify": ("<text>", "Large notification across every player's screen."),

    # ---------------------------------------------------------------- guilds
    "guild create": ('[player] "name"', "Create a guild with the player as leader."),
    "guild delete": ('"name"', "Disband a guild."),
    "guild invite": ('[player] "guild"', "Add a player to a guild."),
    "guild uninvite": ("[player]", "Remove a player from their guild."),
    "guild rank": ("[player] <rank>", "Set a member's rank."),
    "guild rename": ('"old" "new"', "Rename a guild."),
    "guild showlog": ('"guild"', "Recent guild event log."),

    # ---------------------------------------------------------------- events
    "event": ("<event id>", "Status of one game event."),
    "event list": ("", "Every game event and whether it is active."),
    "event start": ("<event id>", "Force an event to start."),
    "event stop": ("<event id>", "Force an event to stop."),
    "event enable": ("<event id>", "Let the event fire on its own schedule."),
    "event disable": ("<event id>", "Keep the event from firing."),

    # ---------------------------------------------------------------- resets
    "reset all": ("spells|talents", "Queue the reset for every character on the realm."),
    "reset honor": ("[player]", "Clear honor points, kills and rank."),
    "reset items": ("[player]", "Strip every item the character owns."),
    "reset level": ("[player]", "Back to level 1 with starting stats."),
    "reset spells": ("[player]", "Back to the class's starting spell book."),
    "reset stats": ("[player]", "Recompute base stats for the current level."),
    "reset talents": ("[player]", "Refund every talent point."),

    # ---------------------------------------------------------------- spam, chat
    "antispam add": ('"phrase" [ban seconds]', "Add a phrase to the spam filter."),
    "antispam remove": ('"phrase"', "Drop a phrase from the filter."),
    "antispam replace": ('"phrase" "replacement"', "Censor a phrase rather than block it."),
    "antispam removereplace": ('"phrase"', "Drop a censor rule."),
    "spamer list": ("", "Accounts the spam filter has flagged."),
    "spamer mute": ("<account>", "Mute a flagged account."),
    "spamer unmute": ("<account>", "Unmute a flagged account."),

    # ---------------------------------------------------------------- misc admin
    "gm list": ("", "Accounts above Player level."),
    "gm ingame": ("", "Game masters currently online and visible."),
    "ticket list": ("", "Open tickets."),
    "ticket onlinelist": ("", "Open tickets whose author is online."),
    "ticket closedlist": ("", "Recently closed tickets."),
    "ticket escalatedlist": ("", "Tickets escalated to a higher level."),
    "ticket viewid": ("<ticket id>", "Read one ticket."),
    "ticket viewname": ("<character>", "Read a character's open ticket."),
    "ticket close": ("<ticket id>", "Close a ticket."),
    "ticket assign": ("<ticket id> <gm>", "Assign a ticket."),
    "ticket unassign": ("<ticket id>", "Release an assigned ticket."),
    "ticket comment": ("<ticket id> <text>", "Attach a GM comment."),
    "ticket delete": ("<ticket id>", "Delete a closed ticket."),
    "ticket reset": ("", "Wipe the ticket queue."),
    "ticket togglesystem": ("", "Accept or refuse new tickets."),
    "ticket reload": ("<ticket id>", "Re-read one ticket from the database."),

    "pdump write": ("<file> <character>", "Write a character to a dump file on the server."),
    "pdump load": ("<file> <account> [name] [guid]", "Load a dump file into an account."),

    "tele name": ("[player] <location>", "Teleport a player to a named game_tele location."),
    "tele del": ("<location>", "Remove a named teleport location."),

    "spell info": ("<spell id>", "Spell template fields."),
    "spell effects": ("<spell id>", "Per-effect breakdown of a spell."),
    "spell search": ("<text>", "Spells matching a name fragment."),

    "variable": ("<name> [value]", "Read a world variable, or set it by passing a value."),
    "service del_characters": ("<flags> <max level> <max money> <max items> "
                               "<max played> <logout days>",
                               "Bulk-delete characters matching every threshold."),
    "groupspell add": ("<group> <spell id>", "Put a spell in a stacking group."),
    "groupspell rule": ("<group> <rule>", "Set a group's stacking rule."),
    "wareffort info": ("", "AQ war effort stage and resource totals."),
    "wareffort setstage": ("<stage>", "Force the war effort stage."),
    "wareffort setgongtime": ("<unix time>", "When the gong becomes usable."),
    "wareffort getresource": ("<resource id> <team>", "One resource's current total."),
    "wareffort setresource": ("<resource id> <amount> <team>", "Overwrite a resource total."),

    "reload all": ("", "Re-read every reloadable table. Heavy; prefer a narrower reload."),
    "reload config": ("", "Re-read mangosd.conf. Only settings marked live take effect."),
    "reload command": ("", "Re-read the command table, including security overrides."),

    # ---------------------------------------------------------------- bots
    "partybot add": ("<class> <role> [level] [spec]",
                     "Spawn a bot into your party. Needs a player session."),
    "partybot clone": ("", "Spawn a bot copied from your selected player."),
    "partybot load": ("<character>", "Bring an existing character in as a bot."),
    "partybot setrole": ("<role>", "Change the selected bot's role."),
    "partybot attackstart": ("", "Send the party at your target, re-issued each tick."),
    "partybot attackstop": ("", "Call the party off."),
    "partybot pull": ("[bot]", "Pull your target with the puller, or the named bot."),
    "partybot setpuller": ("[bot]", "Nominate the bot that pulls."),
    "partybot hold": ("", "Stop the party moving."),
    "partybot release": ("", "Let the party move again."),
    "partybot aoe": ("", "Toggle area spells for the party."),
    "partybot caststart": ("", "Resume casting."),
    "partybot caststop": ("", "Stop casting but stay in combat."),
    "partybot ccmark": ("<mark>", "Crowd control whatever carries this raid mark."),
    "partybot focusmark": ("<mark>", "Focus fire whatever carries this raid mark."),
    "partybot clearmarks": ("", "Drop every crowd control and focus mark."),
    "partybot cometome": ("", "Walk the party to your position."),
    "partybot usegobject": ("", "Have the party use your selected game object."),
    "partybot pause": ("[seconds]", "Suspend bot AI."),
    "partybot unpause": ("", "Resume bot AI."),
    "partybot unequip": ("<item>", "Take an item off the selected bot."),
    "partybot remove": ("", "Remove the selected bot."),
    "partybot removeall": ("", "Remove every party bot you own."),

    "battlebot add alterac": ("<count> [level]", "Add bots to Alterac Valley."),
    "battlebot add arathi": ("<count> [level]", "Add bots to Arathi Basin."),
    "battlebot add warsong": ("<count> [level]", "Add bots to Warsong Gulch."),
    "battlebot removeall": ("", "Remove every battleground bot."),

    "bot add": ("<character>", "Add one world-population bot."),
    "bot add_all": ("", "Add every configured world bot."),
    "bot ranadd": ("<count>", "Add random world bots."),
    "bot delete": ("<character>", "Remove a world bot."),
    "bot info": ("", "World bot counts and state."),
    "bot start": ("", "Start the world bot manager."),
    "bot stop": ("", "Stop the world bot manager."),
    "bot reload": ("", "Re-read the world bot configuration."),

    "raidguild add": ("<name> <race> <class> <gender> <spec> <subgroup> [options]",
                      "Create a persistent raid guild member."),
    "raidguild remove": ("<name>", "Delete a raid guild member."),
    "raidguild list": ("", "Every raid guild member and their spec."),
    "raidguild spec": ("<name> <spec>", "Change a member's spec."),
    "raidguild provision": ("<name>", "Gear and attune a member."),
    "raidguild summon": ("<name>", "Bring a member online and to you."),
    "raidguild dismiss": ("<name>", "Send a member offline."),
    "raidguild status": ("", "Who is online and where."),
    "raidguild guild": ('"guild" <name>', "Move a member into a guild."),
    "raidguild resetbinds": ("<name>", "Clear a member's instance bindings."),
    "raidguild attune": ("<name>", "Grant attunement quests and keys."),
    "raidguild reload": ("", "Re-read the raid guild roster."),
}
